name: github_api
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  fluttericon: ^2.0.0
  github: ^9.24.0
  http: ^1.2.2
  oauth2: ^2.0.3
  url_launcher: ^6.3.1
  window_to_front:
    path: ../window_to_front

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
